### ISSUE TITLE
No forms-flow-forms image for arm64

### ISSUE THREAD

**Issue by echang0929** [AOT-Technologies/forms-flow-ai#1117]
I'm trying to run docker-compose on my Apple M2, but I got an error about forms-flow-forms image supporting only Linux/amd64. Is it possible that I can build a forms-flow-forms image with a Dockerfile?

**Comment by sreehari-aot** [comment]
@echang0929 can you be more specific about the issue you are facing, is it happening for MongoDB or the form server? Please attach the error logs too if any.

**Comment by echang0929** [comment]
Thank you, @sreehari-aot . When I started all containers with docker-compose, I got the following warning:
```
forms-flow-ai/deployment/docker on  master [!] on 🐳 v20.10.21
➜ docker-compose up -d
WARN[0000] The "MT_ADMIN_BASE_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "MT_ADMIN_BASE_URL_VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "DOCUMENT_SERVICE_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "DOCUMENT_SERVICE_URL" variable is not set. Defaulting to a blank string.
[+] Running 9/10
 ⠿ Network docker_forms-flow-network                                                                                                                               Created                             0.0s
 ⠿ Container forms-flow-webapi-db                                                                                                                                  Started                             0.8s
 ⠿ Container forms-flow-bpm-db                                                                                                                                     St...                               0.6s
 ⠿ Container forms-flow-forms-db                                                                                                                                   Started                             0.7s
 ⠿ Container forms-flow-documents-api                                                                                                                              Started                             0.8s
 ⠿ Container forms-flow-bpm                                                                                                                                        Start...                            1.0s
 ⠿ Container forms-flow-forms                                                                                                                                      Sta...                              1.1s
 ⠙ forms-flow-forms The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                     0.0s
 ⠿ Container forms-flow-webapi                                                                                                                                     St...                               1.6s
 ⠿ Container forms-flow-web
```

Just as I mentioned, "forms-flow-forms The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

Then I ignored this warning, but not all containers can start successfully:
```
➜ docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                          PORTS                            NAMES
4e7ae04088e8   docker-forms-flow-web               "/docker-entrypoint.…"   6 minutes ago   Up 6 minutes                    80/tcp, 0.0.0.0:3000->8080/tcp   forms-flow-web
0c17ab894647   docker-forms-flow-webapi            "/wait-for-service.s…"   6 minutes ago   Restarting (1) 12 seconds ago                                    forms-flow-webapi
fb2589e89543   formsflow/forms-flow-forms:v5.0.1   "node main"              6 minutes ago   Up 6 minutes                    0.0.0.0:3001->3001/tcp           forms-flow-forms
a31bf2966837   docker-forms-flow-bpm               "java -Djava.securit…"   6 minutes ago   Restarting (1) 4 seconds ago                                     forms-flow-bpm
f6fd738d79bc   mongo:5.0                           "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes                    0.0.0.0:27018->27017/tcp         forms-flow-forms-db
b25fb2fcb5a9   postgres:11                         "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes                    0.0.0.0:6432->5432/tcp           forms-flow-webapi-db
b2edd085ef44   postgres:latest                     "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes                    0.0.0.0:5432->5432/tcp           forms-flow-bpm-db
cf5a96f589eb   docker-forms-flow-documents-api     "/bin/sh entrypoint"     6 minutes ago   Restarting (1) 34 seconds ago                                    forms-flow-documents-api
```

You see, containers forms-flow-webapi, forms-flow-bpm, forms-flow-documents-api have always restarted. So I tried to check their logs
* forms-flow-webapi
```
...
2023-01-05 08:59:05,530 - app - INFO - Welcome to formsflow-API server...! (app.py:58)
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

* forms-flow-bpm
```
...
.16.jar!/:5.3.16]
	... 94 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/servlet/OAuth2ClientRegistrationRepositoryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal character in authority at index 7: http://{your-ip-address}:8080/auth/realms/forms-flow-ai
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1607) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1571) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1460) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1347) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:759) ~[spring-beans-5.3.16.jar!/:5.3.16]
	... 111 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal character in authority at index 7: http://{your-ip-address}:8080/auth/realms/forms-flow-ai
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.16.jar!/:5.3.16]
	... 127 common frames omitted
Caused by: java.lang.IllegalArgumentException: Illegal character in authority at index 7: http://{your-ip-address}:8080/auth/realms/forms-flow-ai
	at java.base/java.net.URI.create(URI.java:906) ~[na:na]
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.fromIssuerLocation(ClientRegistrations.java:143) ~[spring-security-oauth2-client-5.6.2.jar!/:5.6.2]
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getBuilderFromIssuerIfPossible(OAuth2ClientPropertiesRegistrationAdapter.java:83) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistration(OAuth2ClientPropertiesRegistrationAdapter.java:59) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.lambda$getClientRegistrations$0(OAuth2ClientPropertiesRegistrationAdapter.java:53) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at java.base/java.util.HashMap.forEach(HashMap.java:1421) ~[na:na]
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistrations(OAuth2ClientPropertiesRegistrationAdapter.java:52) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientRegistrationRepositoryConfiguration.clientRegistrationRepository(OAuth2ClientRegistrationRepositoryConfiguration.java:49) ~[spring-boot-autoconfigure-2.6.4.jar!/:2.6.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.16.jar!/:5.3.16]
	... 128 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: http://{your-ip-address}:8080/auth/realms/forms-flow-ai
	at java.base/java.net.URI$Parser.fail(URI.java:2974) ~[na:na]
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3308) ~[na:na]
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3219) ~[na:na]
	at java.base/java.net.URI$Parser.parse(URI.java:3175) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
	at java.base/java.net.URI.create(URI.java:904) ~[na:na]
	... 140 common frames omitted
```

* forms-flow-documents-api
```
...
2023-01-05 09:01:47,058 - app - INFO - Welcome to formsflow-export-API server...! (app.py:58)
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by echang0929** [comment]
Actually, I updated two Dockerfiles so that they can be built successfully:

```
diff --git a/forms-flow-bpm/Dockerfile b/forms-flow-bpm/Dockerfile
index 6ee955d2..3a175a0e 100644
--- a/forms-flow-bpm/Dockerfile
+++ b/forms-flow-bpm/Dockerfile
@@ -11,11 +11,15 @@ COPY src /tmp/src/
 RUN mvn -s /usr/share/maven/ref/settings-docker.xml package -P default

 # Final custom slim java image (for apk command see 17-jdk-alpine-slim)
-FROM openjdk:17-jdk-alpine
+#FROM openjdk:17-jdk-alpine
+FROM openjdk:17-jdk-slim

-ENV JAVA_VERSION=17-ea+14
-ENV JAVA_HOME=/opt/java/openjdk-17\
-    PATH="/opt/java/openjdk-17/bin:$PATH"
+# ENV JAVA_VERSION=17-ea+14
+# ENV JAVA_HOME=/opt/java/openjdk-17\
+#     PATH="/opt/java/openjdk-17/bin:$PATH"
+ENV JAVA_VERSION=17.0.2
+ENV JAVA_HOME=/usr/local/openjdk-17\
+    PATH="/usr/local/openjdk-17/bin:$PATH"

 EXPOSE 8080
 # OpenShift has /app in the image, but it's missing when doing local development - Create it when missing
```

```
diff --git a/forms-flow-documents/Dockerfile b/forms-flow-documents/Dockerfile
index f03fe747..493ea51c 100644
--- a/forms-flow-documents/Dockerfile
+++ b/forms-flow-documents/Dockerfile
@@ -1,5 +1,5 @@
 #Author: Kurian Benoy
-FROM python:3.9-slim-buster
+FROM python:3.9-slim-bullseye

 WORKDIR /forms-flow-documents/app

@@ -21,13 +21,16 @@ RUN CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RE
     ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver

 # Install Google Chrome
-RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
-    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
+## RUN curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
+##    echo "deb http://dl-ssl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
+##    apt-get -yqq update && \
+##    apt-get -yqq install google-chrome-stable && \
+##    rm -rf /var/lib/apt/lists/*
+RUN echo "deb http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list.d/chromium.list && \
     apt-get -yqq update && \
-    apt-get -yqq install google-chrome-stable && \
+    apt-get -yqq install chromium && \
     rm -rf /var/lib/apt/lists/*

-
 # set display port to avoid crash
 ENV DISPLAY=:99
```

**Comment by sreehari-aot** [comment]
@echang0929 You can ignore the warnings. In your container list, there is no Keycloak container showing so I am assuming that you haven't stood up the Keycloak which is a dependency for all other containers. For `forms-flow-forms`  you can try building the image locally.
forms flow-forms:- https://github.com/AOT-Technologies/formio/blob/formsflow-forms/docker-compose.yml
Keycloak- https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-idm/keycloak/docker-compose.yml

**Comment by echang0929** [comment]
I followed the steps on "Local keycloak setup", but I can not start keycloak server:
```
➜ docker logs keycloak -f
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/formsflow-ai-realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
=========================================================================

  Using PostgreSQL database

=========================================================================

10:37:57,138 INFO  [org.jboss.modules] (CLI command executor) JBoss Modules version 1.11.0.Final
10:37:57,447 INFO  [org.jboss.msc] (CLI command executor) JBoss MSC version 1.4.12.Final
10:37:57,474 INFO  [org.jboss.threads] (CLI command executor) JBoss Threads version 2.4.0.Final
10:37:57,834 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) starting
10:37:58,170 INFO  [org.jboss.vfs] (MSC service thread 1-4) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
10:38:00,545 INFO  [org.wildfly.security] (ServerService Thread Pool -- 20) ELY00001: WildFly Elytron version 1.15.3.Final
10:38:02,375 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 9) WFLYCTL0033: Extension 'security' is deprecated and may not be supported in future versions
10:38:03,500 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
10:38:03,881 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
10:38:04,462 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-7) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Used blank.
10:38:04,924 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-6) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-15.0.1.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:38:05,590 INFO  [org.jboss.as.patching] (MSC service thread 1-8) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
10:38:05,798 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-7) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
10:38:06,177 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
10:38:06,183 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) started in 8963ms - Started 59 of 82 services (32 services are lazy, passive or on-demand)
The batch executed successfully
10:38:06,799 INFO  [org.jboss.as] (MSC service thread 1-3) WFLYSRV0050: Keycloak 14.0.0 (WildFly Core 15.0.1.Final) stopped in 54ms
```

**Comment by echang0929** [comment]
Looks like I can use original keycloak project: https://github.com/keycloak/keycloak, I'm going to try it.

**Comment by sreehari-aot** [comment]
@echang0929 formsflow.ai only supports Keycloak 14 as of now, so make sure the version is compatible with formsflow.ai.

**Comment by sreehari-aot** [comment]
@echang0929 Are you able to solve the issue if not can u try the following image for Keycloak
https://hub.docker.com/r/wizzn/keycloak

**Comment by sumesh-aot** [comment]
@echang0929 We have pushed an image for ARM64, docker.io/formsflow/forms-flow-keycloak-arm64:19.0.3, you may use this in your idm docker compose.

**Comment by sreehari-aot** [comment]
Closing this since the last update would fix the issue.

**Comment by echang0929** [comment]
Thank you, @sumesh-aot and @sreehari-aot, I will try it later.
