### ISSUE TITLE
forms-flow-api continually reboots

### ISSUE THREAD

**Issue by F5Brewery** [AOT-Technologies/forms-flow-ai#41]
### Please provide information about your setup

- formsflow.ai Version: latest
- Browser: Not related
- Browser version: net related

### Steps to Reproduce

1.Install configure Keycloak 
2.configure environmental variables for either full docker deployment or just web api docker 
3. Build web-api
4. start web api
5. docker ps -a

### Observed Behaviour
CONTAINER ID   IMAGE                              COMMAND                  CREATED             STATUS                          PORTS                                            NAMES
602a4549b46c   forms-flow-api_forms-flow-webapi   "/bin/sh entrypoint"     15 minutes ago      Restarting (1) 37 seconds ago                                                    forms-flow-api_forms-flow-webapi_1

open the logs:

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package subjectivity to /root/nltk_data...
[nltk_data]   Package subjectivity is already up-to-date!
Configure logging, from conf:/usr/local/lib/python3.8/site-packages/api/logging.conf
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    APP = create_app()
  File "/usr/local/lib/python3.8/site-packages/api/__init__.py", line 27, in create_app
    mongo.init_app(app)
  File "/usr/local/lib/python3.8/site-packages/flask_pymongo/__init__.py", line 147, in init_app
    parsed_uri = uri_parser.parse_uri(uri)
  File "/usr/local/lib/python3.8/site-packages/pymongo/uri_parser.py", line 514, in parse_uri
    nodes = split_hosts(hosts, default_port=default_port)
  File "/usr/local/lib/python3.8/site-packages/pymongo/uri_parser.py", line 364, in split_hosts
    nodes.append(parse_host(entity, port))
  File "/usr/local/lib/python3.8/site-packages/pymongo/uri_parser.py", line 118, in parse_host
    raise ValueError("Port must be an integer between 0 and 65535: %s"
ValueError: Port must be an integer between 0 and 65535: port

### Expected Behaviour

For it to start running and be accessable on 5000

**Comment by F5Brewery** [comment]
OK found the issue, but it is not clear for me.
The mongodb URI needs populated.  It appears to be launched though and I do not see where or how this populated in order for me to get the correct info.  I filled it in with bogus stuff and it got by it presumably until I try to use a sentiment?

It would be nice to have some additional detail on the mongodb

I also need to figure a way to get my keycloak self signed SSL over to this machine.  For now I am running it separate with its own keycloak over 8080 and it is working.

**Comment by F5Brewery** [comment]
I effectively solved this by creating a second set of environment variables in the .env and yml for web_api having it point to the http version.  I could not figure out how to add my root cert to the docker container as my docker knowledge is still little.

I wish there was a forum or other place to go for assistance.  I have it all up, sort of.  My workflows don't show when I try to associate - just says "No Data Available" leaves me wandering if it connects back to my mongodb issue

**Comment by F5Brewery** [comment]
I solved it further by mounting my certs folder into the web api docker container through the yaml file - 
 - /etc/ssl/certs:/etc/ssl/certs

Then adding:
update-ca-certificates 
before the last line of entrypoint in the web-api folder.
