### ISSUE TITLE
Included Workflows do not function

### ISSUE THREAD

**Issue by F5Brewery** [AOT-Technologies/forms-flow-ai#47]
### Please provide information about your setup

- formsflow.ai Version: Docker Full Deployment
- Browser: Chrome/IE
- Browser version: Latest

### Steps to Reproduce

1.Full install according to instruction
2.Create Form and attach any of the included workflows, save
3.Use form and submit

### Observed Behaviour
No task shows up
Errors on Web API with 500 internal server error are received. In camunda this is a bit ambiguous.

If possible provide a screenshot to demonstrate the bug.

### Expected Behaviour
Task to be assigned to a particular group

###Note###
If one creates a basic user task it does function and it does show in the forms task list at least for a designer.

**Comment by F5Brewery** [comment]
As you can tell I am quite dedicated to make this work.  
I have a suspicion that something is going awry in SequenceFlow_0ociprs.
What type of value is expected for the applicationId?  I tried something from Formio, but I got an error:
{"type":"RestException","message":"Cannot instantiate process definition one_step_review:6:541ad592-72f9-11eb-a558-02te event listener : Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of VALUE_NUMBER_INT token\n at [Source: (String)\"16\"; line: 1, column: 1]"}
I totally do not expect that to work...to just replace the value, but was hoping it would lead me further down a path of possibilities.

**Comment by F5Brewery** [comment]
[WebAPI.logs.txt](https://github.com/AOT-Technologies/forms-flow-ai/files/6030961/WebAPI.logs.txt)
[BPM.logs.txt](https://github.com/AOT-Technologies/forms-flow-ai/files/6030960/BPM.logs.txt)
In case others also run into this maybe we can work on this together?  I may effectively start dissecting this to resolve and just fork it.  As it stands if I use one of the builtin workflows it throws the errors in these logs and it does not show in tasks.  It looks like these workflows are using some processes that fill information in form.io, as this is missing in my self created that successfully runs.  I can also see them listed in the workflow designer of the existing workflows.

**Comment by F5Brewery** [comment]
If anyone is paying attention to this and thinks...Maybe making camunda/BPM an SSL site will fix it, nope.  Its more trouble and you end up with the same error.
I think I will go back to looking into the WebAPI - This error intrigues me and makes me believe it is not creating something...
2021-02-24 16:06:58,981 - root - ERROR in logging:logging.py:19 - log_error: ERROR:Create - status_code: 500, {"type":"NotFound","message":"404 Not Found: [<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot PUT /form/</pre>\n</body>\n</html>\n]"}https://workflow.twistinc.net:443/camunda/engine-rest/process-definition/key/one_step_review/start
2021-02-24 16:06:58,982 - api - ERROR in app:app.py:1890 - log_exception: Exception on /application/create [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restx/cors.py", line 45, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/flask_jwt_oidc/jwt_manager.py", line 227, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/api/utils/auth.py", line 28, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/api/resources/application.py", line 164, in post
    application = ApplicationService.create_application(dict_data, request.headers["Authorization"])
  File "/usr/local/lib/python3.8/site-packages/api/services/application.py", line 32, in create_application
    application.update({'process_instance_id': response['id']})
TypeError: 'NoneType' object is not subscriptable
May just go in a different direction though.

**Comment by abhilash-aot** [comment]
This will be fixed in version 4. Will update generic workflows
